version: "3.9"
services:
  tensorflow:
    build: ./python-model
    ports:
      - 8000:8000
    volumes:
      - ./python-model:/app
    environment:
      FLASK_ENV: development
  react-app:
    build: ./number-classifier
    ports:
      - 3000:3000
    volumes:
      - ./number-classifier:/user/src/app
    depends_on:
      - tensorflow
